"""add column conutry

Revision ID: a0ac4cb8ae0c
Revises: 
Create Date: 2024-08-12 21:27:51.405086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ac4cb8ae0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cars_description', table_name='cars')
    op.drop_index('ix_cars_title', table_name='cars')
    op.drop_table('cars')
    op.add_column('car_brands', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_brands', 'country')
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='cars_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.create_index('ix_cars_title', 'cars', ['title'], unique=False)
    op.create_index('ix_cars_description', 'cars', ['description'], unique=False)
    # ### end Alembic commands ###
